# Generated by Django 5.1.2 on 2024-11-30 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('artist', models.CharField(max_length=512)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('format', models.CharField(choices=[('DD', 'Digital Download'), ('CD', 'Compact Disk'), ('VL', 'Vinyl')], max_length=2)),
                ('releaseDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('runningTime', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlbumTrackListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label_music_manager.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label_music_manager.song')),
            ],
        ),
    ]
