# Generated by Django 5.1.2 on 2024-12-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0002_album_cover_album_slug_album_tracks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=512, unique=True),
        ),
    ]
