# Generated by Django 5.1.2 on 2024-12-01 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0004_alter_album_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='slug',
        ),
    ]
