# Generated by Django 5.1.2 on 2024-12-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0005_remove_album_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=512, unique=True),
            preserve_default=False,
        ),
    ]
