# Generated by Django 5.1.2 on 2024-12-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0006_album_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumtracklistitem',
            options={'ordering': ['position']},
        ),
    ]
