# Generated by Django 5.1.2 on 2024-12-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0008_musicmanageruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmanageruser',
            name='display_name',
            field=models.CharField(default='', max_length=512),
        ),
    ]
