# Generated by Django 5.1.2 on 2024-12-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0009_musicmanageruser_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='releaseDate',
            new_name='release_date',
        ),
    ]
